version: '3'

volumes:
  database_data:
    driver: local
  static_data:
    driver: local

services:
  tomcat:
    build:
      context: .
      dockerfile: Dockerfile-tomcat
    restart: always
    ports:
      - 8000:8000
    volumes:
      - static_data:/var/www/static
    links:
      - postgresql
    environment:
      JPDA_ADDRESS: 8000
      JPDA_TRANSPORT: dt_socket
    command: [catalina.sh, jpda, run]

  nginx:
    build:
      context: .
      dockerfile: Dockerfile-nginx
    restart: always
    ports:
      - 8080:8080
    volumes:
      - static_data:/var/www/static
    links:
      - tomcat


  postgresql:
    image: postgres:latest
    restart: always
    ports:
        - 5432:5432
    volumes:
      - database_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: violet
      POSTGRES_PASSWORD: violet
      POSTGRES_DB: violet