FROM tomcat:7

# Remove factory webapps (besides the manager) so we can add our own as the root app
RUN cd "$CATALINA_HOME/webapps"\
	&& find . -maxdepth 1 -mindepth 1 ! -name 'manager' -exec rm -rf {} +
	
COPY tomcat-users.xml "$CATALINA_HOME/conf/"

CMD ["catalina.sh", "jpda", "run"]